<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="exec" nsURI="ecore://nasdanika.org/core/exec" nsPrefix="org.nasdanika.exec">
  <eAnnotations source="urn:org.nasdanika">
    <details key="documentation-reference" value="doc/package-summary.md"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//ModelElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/block.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="try" lowerBound="1" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="catch" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="finally" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Call" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//ModelElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/call.md"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="service_property_class method_arguments"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="urn:org.nasdanika">
        <details key="feature-key" value="class"/>
        <details key="exclusive-with" value="service property"/>
        <details key="default-feature" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Fully qualified class name. Mutually exclusive with ``service`` and ``property``. One of ``class``, ``property``, or ``service`` is required.&#xA;&#xA;For SupplierFactory adapter, if the class implements SupplierFactory then it is instantiated and then its ``create()`` method is invoked to create a supplier.&#xA;If the class implements Supplier, then it is instantiated. If there are no ``init`` arguments, then the supplier is diagnosed as part of ``diagnose()``. &#xA;Otherwise it is diagnosed in ``execute()`` and diagnostic results are discarded.&#xA;&#xA;Similar processing will be implemented for Consumer and Command.&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="property" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="urn:org.nasdanika">
        <details key="exclusive-with" value="class service"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Context property name. Mutually exclusive with ``class`` and ``service``. One of ``class``, ``property``, or ``service`` is required."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="service" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="urn:org.nasdanika">
        <details key="exclusive-with" value="class property"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Fully qualified context service class name. Mutually exclusive with ``class`` and ``property``. One of ``class``, ``property``, or ``service`` is required."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An optional method to call. In the ``class`` case the method can be static. If the method is static the class is not instantiated and if ``init`` or ``properties`` are present it results in an exception."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A map injected into the instance in the ``class`` case if the instance implements ${javadoc/java.util.function.BiConsumer} or in the service or property case if they implement SupplierFactory. If elements implement SupplierFactory then the supplier factory is used to produce value to be injected. Otherwise elements are injected AS-IS."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="init" upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="exclusive-with" value="service property"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An optional array of constructor arguments for the ``class``. Not applicable for ``property`` and ``service``. If elements implement SupplierFactory then the factory is used to produce argument values. Then arguments get converted to constructor parameter types if conversion is available. If conversion is not available, an exception is thrown."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An optional array of method arguments. If elements implement SupplierFactory, then the factory is used to produce argument value. Then arguments get converted to method parameter types if conversion is available. If conversion is not available, an exception is thrown."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" instanceClassName="java.util.Map$Entry">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/property.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Configurator" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//ModelElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/configurator.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Component to execute with the augmented context."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A map injected into the instance in the ``class`` case if the instance implements java.util.function.BiConsumer or in the service or property case if they implement SupplierFactory. &#xA;If elements implement SupplierFactory then the supplier factory is used to produce value to be injected. Otherwise elements are injected AS-IS."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Eval" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//ModelElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/eval.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="script" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Script source"/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="default-feature" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
        eType="#//Property" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Script bindings. Context is available as ``context`` binding and progress monitor as ``progressMonitor`` binding."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fail" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//ModelElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/fail.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="urn:org.nasdanika">
        <details key="default-feature" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Message to output. Interpolated."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="List" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//ModelElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/list.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" lowerBound="1"
        upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Map" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//ModelElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/map.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
        eType="#//Property" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Map entries."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eSubpackages name="content" nsURI="ecore://nasdanika.org/core/exec/content" nsPrefix="org.nasdanika.exec.content">
    <eClassifiers xsi:type="ecore:EClass" name="Filter" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//ModelElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Base class for filters which take an object, adapt to ${javadoc/org.nasdanika.common.SupplierFactory}&lt;InputStream>, obtain a stream and produce another stream from it."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
          eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Source to be filtered. The source is adapted to ${javadoc/org.nasdanika.common.SupplierFactory}&lt;InputStream>."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Base64" eSuperTypes="#//content/Filter">
      <eAnnotations source="urn:org.nasdanika">
        <details key="documentation-reference" value="doc/content/base-64.md"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//ModelElement">
      <eAnnotations source="urn:org.nasdanika">
        <details key="documentation-reference" value="doc/content/resource.md"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Resource location resolved relative to the model resource location."/>
        </eAnnotations>
        <eAnnotations source="urn:org.nasdanika">
          <details key="default-feature" value="true"/>
          <details key="resolve-uri" value="true"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="interpolate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="If true, location is interpolated. Default is false."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="errorMessage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="If set, the message content is used as resource content if there is an error loading the resource content. The message is interpolated with url and exception tokens."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Text" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//ModelElement">
      <eAnnotations source="urn:org.nasdanika">
        <details key="documentation-reference" value="doc/content/text.md"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Text content."/>
        </eAnnotations>
        <eAnnotations source="urn:org.nasdanika">
          <details key="default-feature" value="true"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="interpolate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="If ``true`` (default), content is interpolated."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Interpolator" eSuperTypes="#//content/Filter">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Converts input stream to String using the context charset, which defaults to ``UTF-8``, interpolates, and converts back to input stream using the context charset."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="load-doc-reference" value="doc/content/interpolator-load-doc.md"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="processIncludes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true">
        <eAnnotations source="urn:org.nasdanika">
          <details key="documentation-reference" value="doc/content/interpolator--process-includes.md"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="base" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Optional base URL for resolving include and image URL's. &#xA;If the base is blank then marker location is used as the base, if marker is present and location is not null. &#xA;Otherwise, resource URL is used as the base. &#xA;Marker location is the URL of a YAML resource from which interpolator specification was loaded. &#xA;It may be different from the resource URL if a model was loaded from YAML and then saved to XML.&#xA;&#xA;If the base is not blank then it is resolved relative to the marker location if it starts with ``./`` and marker location is not null or the resource base otherwise.&#xA;"/>
        </eAnnotations>
        <eAnnotations source="urn:org.nasdanika">
          <details key="resolve-uri" value="true"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Markdown" eSuperTypes="#//content/Filter">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="style" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="resources" nsURI="ecore://nasdanika.org/core/exec/resources"
      nsPrefix="org.nasdanika.exec.resources">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/resources/package-summary.md"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//ModelElement">
      <eAnnotations source="urn:org.nasdanika">
        <details key="documentation-reference" value="doc/resources/resource.md"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Resource name. Interpolated."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
          eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Resource contents. File contents elements are adapted to ``SupplierFactory`` and produced ``InputStream``s are contcatenated. Container contents elements are adapted to ConsumerFactory and the container is passed to their ``execute`` method."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="reconcileAction" eType="#//resources/ReconcileAction"
          defaultValueLiteral="Overwrite">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Reconcile action - what to do if a resource with the same name already exists. Defalut is ``Overwrite``."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="merger" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
          containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Merger for ``Merge`` reconcile action. Adapted to ``org.nasdanika.common.resources.Merger`` to execute actual merge."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Container" eSuperTypes="#//resources/Resource">
      <eAnnotations source="urn:org.nasdanika">
        <details key="documentation-reference" value="doc/resources/container.md"/>
      </eAnnotations>
      <eOperations name="getContainer" eType="#//resources/Container">
        <eParameters name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="getFile" eType="#//resources/File">
        <eParameters name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="find" eType="#//resources/Resource">
        <eParameters name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="File" eSuperTypes="#//resources/Resource">
      <eAnnotations source="urn:org.nasdanika">
        <details key="documentation-reference" value="doc/resources/file.md"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ReconcileAction">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Defines an action to take when a resource with the same name already exists."/>
      </eAnnotations>
      <eLiterals name="Append">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Appends new content to the existing content. For containers it means that new resources will be placed in the container next to the existing resources. For files it means that the new content will be appended after the existing content."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals name="Cancel" value="1">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Cancels execution if resource already exists."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals name="Keep" value="2">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Keeps the existing resource intact."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals name="Merge" value="3">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Merges old and new content of a file using a built-in or provided ``org.nasdanika.common.resources.Merger``. Merger is obtained from ``merger`` reference. For containers Merge is the same as Append."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals name="Overwrite" value="5">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Overwrites existing resource. For containers - deletes their contents."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals name="Rename" value="6">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Renames existing resource. For containers the same as Append."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals name="Dedup" value="7">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Keeps the existing resource. Saves a new resource with a different name, e.g. adding a timestamps at the end."/>
        </eAnnotations>
      </eLiterals>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
