<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ncore" nsURI="urn:org.nasdanika.ncore" nsPrefix="org.nasdanika.ncore">
  <eAnnotations source="urn:org.nasdanika">
    <details key="documentation-reference" value="doc/package-summary.md"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Adaptable" instanceClassName="org.nasdanika.common.Adaptable"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IMarked" instanceClassName="org.nasdanika.common.persistence.Marked"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Marked" abstract="true" interface="true"
      eSuperTypes="#//IMarked">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/marked.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="marker" eType="#//Marker"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IMarker" instanceClassName="org.nasdanika.common.persistence.Marker"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Marker" eSuperTypes="#//IMarker">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="line" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Instant" instanceClassName="java.time.Instant">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="[Instant](https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html) is a single instantaneous point on the time-line. &#xA;If instant specification contains ``Z``, then it is parsed using [Instant.parse()](https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html#parse-java.lang.CharSequence-) method.&#xA;Otherwise the specification is used to construct ``java.util.Date`` which is then converted to instant.&#xA;&#xA;Examples:&#xA;&#xA;* ``2021-12-03T10:15:30.00Z`` - loaded using ``Instant.parse()``&#xA;* ``10/1/2021`` - loaded using ``new Date()`` and then converted to instant.&#xA;&#xA;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Duration" instanceClassName="java.time.Duration">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="[Duration](https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html) is an amount of time in the [ISO-8601 Duration format](https://en.wikipedia.org/wiki/ISO_8601#Duration). Supports days and smaller units. Weeks, months and years are not supported. Example: ``P28DT10H``."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Temporal" eSuperTypes="#//ModelElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/temporal.md"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="bounds offset"/>
    </eAnnotations>
    <eOperations name="after" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Tests if this temporal is after the specified temporal. Returns null if unknown, e.g. two unrelated events."/>
      </eAnnotations>
      <eParameters name="when" eType="#//Temporal"/>
    </eOperations>
    <eOperations name="before" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Tests if this temporal is before the specified temporal. Returns null if unknown, e.g. two unrelated events."/>
      </eAnnotations>
      <eParameters name="when" eType="#//Temporal"/>
    </eOperations>
    <eOperations name="coincides" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Tests if this temporal occurs at the same point on the time-line as the specified temporal. Returns null if unknown, e.g. two unrelated events."/>
      </eAnnotations>
      <eParameters name="when" eType="#//Temporal"/>
    </eOperations>
    <eOperations name="normalize" eType="#//Temporal">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns a normalized instance of this temporal not contained in the model. Normalization walks through the temporal chain to the root temporal. If that root temporal is instant/absolute then the normalized instance would be instant/absolute. Otherwise the normalized instance would contain the root temporal as its base and offset would be the sum of all offsets."/>
      </eAnnotations>
    </eOperations>
    <eOperations name="minus" eType="#//Duration">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns [duration](Duration.html) difference between this temporal and the argument temporal - how much this temporal is after the argument on the time-line, if difference can be computed, e.g. both this temporal and the argument temporal are instant or trace to the same base temporal. Returns null otherwise."/>
      </eAnnotations>
      <eParameters name="when" eType="#//Temporal"/>
    </eOperations>
    <eOperations name="minus" eType="#//Temporal">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns a temporal based on this one offset by negation of the argument [duration](Duration.html). Null duration is treated as zero and set as-is (not negated)."/>
      </eAnnotations>
      <eParameters name="offset" eType="#//Duration"/>
    </eOperations>
    <eOperations name="plus" eType="#//Temporal">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns a temporal based on this one offset by the argument [duration](Duration.html). Duration can be null."/>
      </eAnnotations>
      <eParameters name="offset" eType="#//Duration"/>
    </eOperations>
    <eOperations name="copy" eType="#//Temporal">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns a deep copy of self with bounds copied. Other containment references are not set."/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instant" eType="#//Instant">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An absolute point on the time-line. E.g. ``2021/07/04``."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="default-feature" value="true"/>
        <details key="exclusive-with" value="base"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base" eType="#//Temporal"
        eOpposite="#//Temporal/derivatives">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Base of this temporal."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="exclusive-with" value="instant"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" eType="#//Duration">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Time offset from the base in [ISO-8601 durations](https://en.wikipedia.org/wiki/ISO_8601#Durations) format. &#xA;&#xA;Examples:&#xA;&#xA;* ``P1H`` for one hour later.&#xA;* ``-P20D`` or ``P-20D`` for 20 days before. Can be null (zero), e.g. if one [period](Period.html) starts right after another period ends."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="derivatives" upperBound="-1"
        eType="#//Temporal" derived="true" eOpposite="#//Temporal/base">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Temporals which are based on this temporal."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lowerBounds" upperBound="-1"
        eType="#//Temporal" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Lower bounds of a temporal. E.g. exact time of some temporal might not be known at a moment, but it might be known that it should not be before than some other temporal - a lower bound. Lower bounds are used in validations and before/after computations. "/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
        <details key="strict-containment" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upperBounds" upperBound="-1"
        eType="#//Temporal" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Upper bounds of a temporal. E.g. exact time of some temporal might not be known at a moment, but it might be known that it should not be after some other temporal - an upper bound. Upper bounds are used in validations and before/after computations. "/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
        <details key="strict-containment" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Period" eSuperTypes="#//ModelElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/period.md"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="start_end"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//Temporal"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Period start."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
        <details key="strict-containment" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//Temporal"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Period end."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
        <details key="strict-containment" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="#//Duration">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Positive period duration in [ISO-8601 durations](https://en.wikipedia.org/wiki/ISO_8601#Durations) format. E.g. ``P1M`` for one month or ``P20D`` for 20 days."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" abstract="true" eSuperTypes="#//Marked #//Adaptable">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/model-element.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If element's URI is not set then its default value is derived from the container URI and containment reference. &#xA;This is a logical URI and it can be used for cross-referencing of elements in a resource-independent fashion.&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Description in HTML."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uuid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" eSuperTypes="#//ModelElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/named-element.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Element name."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference">
    <eTypeParameters name="T"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1">
      <eAnnotations source="urn:org.nasdanika">
        <details key="default-feature" value="true"/>
      </eAnnotations>
      <eGenericType eTypeParameter="#//Reference/T"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="String">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="urn:org.nasdanika">
        <details key="default-feature" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="List">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="urn:org.nasdanika">
        <details key="reference-type" value="map: Map&#xA;list: List&#xA;string: String"/>
        <details key="value-feature" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Map">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//Property" eKeys="#//Property/name">
      <eAnnotations source="urn:org.nasdanika">
        <details key="reference-type" value="map: MapProperty&#xA;list: ListProperty&#xA;string: StringProperty"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringProperty" eSuperTypes="#//Property #//String"/>
  <eClassifiers xsi:type="ecore:EClass" name="MapProperty" eSuperTypes="#//Property #//Map"/>
  <eClassifiers xsi:type="ecore:EClass" name="ListProperty" eSuperTypes="#//Property #//List"/>
</ecore:EPackage>
