<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tree" nsURI="urn:org.nasdanika.sirius.tree" nsPrefix="org.nasdanika.sirius.tree">
  <eClassifiers xsi:type="ecore:EClass" name="AdapterFactoryTree" eSuperTypes="../../org.eclipse.sirius/model/viewpoint.ecore#//DRepresentation ../../org.eclipse.sirius/model/viewpoint.ecore#//DSemanticDecorator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="#//AdapterFactoryTreeDescription"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdapterFactoryTreeDescription" eSuperTypes="../../org.eclipse.sirius/model/viewpoint.ecore#//description/RepresentationDescription">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="editorId" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="org.nasdanika.emf.presentation.AdapterFactoryTreeEditor.ID"/>
  </eClassifiers>
</ecore:EPackage>
