<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="provisioning" nsURI="urn:org.nasdanika.provisioning" nsPrefix="org.nasdanika.provisioning">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Provisioning model. Capabilities, requirements, capability providers, provisioning plans. E.g. for a requirement of a 1/8 hole there might be a provisioning plan to buy a drill and do it yourself and another to call a handyman. "/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Capability" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Capability is something required by an issue."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredBy" upperBound="-1"
        eType="#//Requirement" eOpposite="#//Requirement/requiredCapabilities">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Activities using/leveraging this resource."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Пользователи"/>
        <details key="documentation_ru" value="Работы и операции использующие данный ресурс."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Requirement of a zero or more capabilities."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredCapabilities" upperBound="-1"
        eType="#//Capability" eOpposite="#//Capability/requiredBy">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Capabilities needed to satisfy the requirement."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
