<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="provisioning" nsURI="urn:org.nasdanika.provisioning" nsPrefix="org.nasdanika.provisioning">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Provisioning model."/>
  </eAnnotations>
  <eAnnotations source="urn:org.nasdanika">
    <details key="label_ru" value="Nasdanika.Ригель"/>
    <details key="Documentation_ru" value="Nasdanika Rigel -  инструмент моделирования, описания и контраля выполнения рабочих потоков и процессов. "/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base class for other model elements."/>
    </eAnnotations>
    <eAnnotations source="urn:org.nasdanika">
      <details key="label_ru" value="Элемент модели"/>
      <details key="Documentation_ru" value="Базовый класс для других элементов модели"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Element name. "/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Наименование"/>
        <details key="Documentation_ru" value="Наименование элемента модели"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Optional element URL. Resolved relative to the containing element URL. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Element description in [markdown](https://en.wikipedia.org/wiki/Markdown)."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Описание"/>
        <details key="Documentation_ru" value="Описание элемента модели с использованием синтаксиса [markdown](https://en.wikipedia.org/wiki/Markdown)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="configuration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Element configuration in [YAML](https://en.wikipedia.org/wiki/YAML). Configuration is element-specific and it can be used for, say, analysis or runtime configuration. "/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Конфигурация"/>
        <details key="Documentation_ru" value="*Конфигурация* элемента в [YAML] (https://en.wikipedia.org/wiki/YAML). Конфигурация зависит от элемента и может использоваться, например, для анализа или конфигурации во время выполнения."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageElement" abstract="true" eSuperTypes="#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Model element which can be contained by a package."/>
    </eAnnotations>
    <eAnnotations source="urn:org.nasdanika">
      <details key="label_ru" value="Упакованный элемент"/>
      <details key="Documentation_ru" value="Элемент модели, котрый может быть включен в пакет"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associations" upperBound="-1"
        eType="#//Association" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EngineeredElement" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base class for elements which have an owning engineer and may contain issues."/>
    </eAnnotations>
    <eAnnotations source="urn:org.nasdanika">
      <details key="label_ru" value="?Управляемый элемент"/>
      <details key="Documentation_ru" value="Базовый класс для элемента модели, владельцем которого является инженер. Может содержать проблеммы/задачи."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owners" upperBound="-1"
        eType="#//Engineer" eOpposite="#//Engineer/owns">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Engineer responsible for this element."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Инженер"/>
        <details key="Documentation_ru" value="Инженер, владелец этого элемента."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="issues" upperBound="-1"
        eType="#//Issue" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issues associated with the element - problems/pain points, improvement opportunities/enhancements."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Проблемы"/>
        <details key="Documentation_ru" value="Проблемы, связанные с элементом - проблемы / болевые точки, возможности улучшения / улучшения."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IPackage" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract container of package elements."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//PackageElement" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Container elements."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Элементы пакета"/>
        <details key="documentation_ru" value="Элементы пакета"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="#//PackageElement #//EngineeredElement #//IPackage">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Container of package elements."/>
    </eAnnotations>
    <eAnnotations source="urn:org.nasdanika">
      <details key="label_ru" value="Пакет"/>
      <details key="documentation_ru" value="Пакет содержит элементы модели."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Participant" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="flows" upperBound="-1"
        eType="#//Flow" eOpposite="#//Flow/paricipants">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Activities in which this actor participates."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Действия"/>
        <details key="documentation_ru" value="Действия в которых участвует исполнитель"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//PackageElement #//EngineeredElement #//Participant">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Actors perform activities using resources consuming and producing artifacts."/>
    </eAnnotations>
    <eAnnotations source="urn:org.nasdanika">
      <details key="label_ru" value="Исполнитель"/>
      <details key="documentation_ru" value="Лицо, осуществляющее действия, используя ресурсы и производя артефакты"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Capability" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Capability is something required by an issue."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredBy" upperBound="-1"
        eType="#//Requirement" eOpposite="#//Requirement/requiredCapabilities">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Activities using/leveraging this resource."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Пользователи"/>
        <details key="documentation_ru" value="Работы и операции использующие данный ресурс."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Requirement of a zero or more capabilities."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredCapabilities" upperBound="-1"
        eType="#//Capability" eOpposite="#//Capability/requiredBy">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Capabilities needed to satisfy the requirement."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Flow" abstract="true" eSuperTypes="#//PackageElement #//EngineeredElement #//Requirement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Flow is an abstract container of flow elements."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//FlowElement" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Flows are composed from flow elements."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Операция"/>
        <details key="documentation_ru" value="Работа может быть разделена на составляющие её операции."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paricipants" upperBound="-1"
        eType="#//Participant" eOpposite="#//Participant/flows">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="One or more actors participate in completion of a flow."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Участники"/>
        <details key="documentation_ru" value="Один или более исполнителей, участвующих в выполнении работы."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The sum of total sizes of this flow children plus the size of self if instance of activity."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Суммарный размер"/>
        <details key="documentation_ru" value="Сумма размеров всех дочерних элементов работы"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalProgress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Calculated total flow progress in percent. "/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Суммарный прогресс"/>
        <details key="documentation_ru" value="Суммарная оценка прогресса всей работы (с учетом размера и важности дочерних операций)"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowElement" abstract="true" eSuperTypes="#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Element of a (composite) activity."/>
    </eAnnotations>
    <eAnnotations source="urn:org.nasdanika">
      <details key="label_ru" value="Операция"/>
      <details key="documentation_ru" value="Операция - это элемент сложного (составного) действия"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Source" abstract="true" eSuperTypes="#//FlowElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Source of transitions."/>
    </eAnnotations>
    <eAnnotations source="urn:org.nasdanika">
      <details key="label_ru" value="Источник"/>
      <details key="documentation_ru" value="Источник (чего?) Точка входа?"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outboundTransitions" upperBound="-1"
        eType="#//Transition" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Outbound transitions."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Исходящие"/>
        <details key="documentation_ru" value="Исходящие (что?) Точки выхода?"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="#//Artifact" eOpposite="#//Artifact/producers">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Artifacts output/produced by this source."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Артефакт"/>
        <details key="documentation_ru" value="Артефакты производимые этим источником"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Start" eSuperTypes="#//PackageElement #//Source">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Start pseudo-activity."/>
    </eAnnotations>
    <eAnnotations source="urn:org.nasdanika">
      <details key="label_ru" value="Старт"/>
      <details key="documentation_ru" value="Старт псевдо- активности"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Target" abstract="true" eSuperTypes="#//FlowElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Target of transitions."/>
    </eAnnotations>
    <eAnnotations source="urn:org.nasdanika">
      <details key="label_ru" value="Цель"/>
      <details key="documentation_ru" value="Цель передачи потока данных и  артефактов"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inboundTransitions" upperBound="-1"
        eType="#//Transition" eOpposite="#//Transition/target">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Inbound transitions."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Вход в работу/операцию"/>
        <details key="documentation_ru" value="???Inbound transitions."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//Artifact" eOpposite="#//Artifact/consumers">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Input artifacts consumed by this target."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Входящие артефакты"/>
        <details key="documentation_ru" value="Входящие артефакты необходимые для выполнения целевого этапа работы"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="End" eSuperTypes="#//PackageElement #//Target">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="End pseudo-activity."/>
    </eAnnotations>
    <eAnnotations source="urn:org.nasdanika">
      <details key="label_ru" value="Конец работы"/>
      <details key="documentation_ru" value="Элемент завершающий псевдо-активность"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Partition" eSuperTypes="#//Flow #//FlowElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Partition is a grouping of flow elements associating participants and resources with the contained elements. "/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="#//Flow #//Source #//Target">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="By performing an activity participants produce outputs from inputs using resources."/>
    </eAnnotations>
    <eAnnotations source="urn:org.nasdanika">
      <details key="label_ru" value="Работа"/>
      <details key="documentation_ru" value="Работа - это то, что необходимо для получения желаемого результата. &#xA;&#xA;Выполняя действие исполнитель получает входящие артефакты, использует ресурсы и создаёт исходящие артефакты, являющиеся промежуточными или конечными результатами процесса.&#xA;&#xA;Варианты перевода:&#xA;&#xA;&#xA;* Действие / Элементарное действие&#xA;* Процесс/Операция&#xA;* Работа / Операция "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Activity size in some unit used by all activities. For example - hours, points, dollars."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Размер"/>
        <details key="documentation_ru" value="Оценка работы / операции в каких-либо единицах: трудо-часах, присестах, деньгах."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="progress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Activity progress in percent. Value between 0 and 100. Progress can be used in &quot;instance&quot; models which are used to model and track execution of an actual effort as opposed to &quot;template&quot; models which explain steps to complete an effort."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Прогресс"/>
        <details key="documentation_ru" value="Оценка степени выполнения работы/ операции в процентах. Значение между 0 и 100. &#xA;&#xA;&#xA;Прогресс может быть использован для оценки практического выполнения рабочего потока. &#xA;&#xA;Для этого на основании смоделированного шаблона, описывающего этапы выполнения работы создается &quot;Действующий экземпляр&quot; рабочего потока, в котором оцениваются фактические затраты артефактов, материалов, ресурсов и прогресс выполнения. &#xA;&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Milestone" eSuperTypes="#//PackageElement #//Source #//Target">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A milestone shows an important achievement in a flow. &#xA;The milestones represent a sequence of events that incrementally build up until flow completion."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The sum of size of all activities which need to be completed to reach this milestone from the start of the previous milestone(s)."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Суммарный размер"/>
        <details key="documentation_ru" value="Сумма размеров всех дочерних элементов работы"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="progress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Calculated total progress toward achiveing the milestone in percent. "/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Суммарный прогресс"/>
        <details key="documentation_ru" value="Суммарная оценка прогресса всей работы (с учетом размера и важности дочерних операций)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="missed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="True if target date is set, the current date is after the target date and progress is less than 100%"/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Суммарный размер"/>
        <details key="documentation_ru" value="Сумма размеров всех дочерних элементов работы"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityReference" eSuperTypes="#//PackageElement #//Source #//Target">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="References a shared activity defined elsewhere."/>
    </eAnnotations>
    <eAnnotations source="urn:org.nasdanika">
      <details key="label_ru" value="Ссылка на работу"/>
      <details key="documentation_ru" value="???Ссылка на общий вид деятельности, определенный в другом месте."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" eType="#//Activity">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="By performing an activity participants produce outputs from inputs using resources."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Работа"/>
        <details key="documentation_ru" value="Выполняя работу исполнители производят исходящие (целевые) артефакты, используя входящие артефакты и ресурсы."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Artifact" eSuperTypes="#//PackageElement #//EngineeredElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Artifact is something output/produced by a source and consumed by a target as input. For example - source code, user guide, binary code. Artifacts are passed between activities over transitions."/>
    </eAnnotations>
    <eAnnotations source="urn:org.nasdanika">
      <details key="label_ru" value="Артефакт"/>
      <details key="documentation_ru" value="Артефакт - это что-то, что выводится / генерируется источником и используется целью в качестве входных данных. &#xA;&#xA;Например - исходный код, руководство пользователя, двоичный код. &#xA;&#xA;*Артефакт - это промежуточный результат, который передается от предшествующей операции (источника) к последующей операции (цели).*&#xA;&#xA;Артефакты передаются между действиями через переходы."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="consumers" upperBound="-1"
        eType="#//Target" eOpposite="#//Target/inputs">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Targets consuming this artifact as their input."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Потребители"/>
        <details key="documentation_ru" value="Работы или операции для которых данный аритефакт является входящим."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="producers" upperBound="-1"
        eType="#//Source" eOpposite="#//Source/outputs">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Sources emitting this artifact as their output."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Производители"/>
        <details key="documentation_ru" value="Работа или операция результатом которой является данный артефакт"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Artifact" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Artifacts can be nested. E.g. a zip archive contains directories which contain files."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Вложенные артефакты"/>
        <details key="documentation_ru" value="Артефакты могут быть вложенными друг в друга. Например: zip, содержащий папки, содержащие файлы."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="#//PackageElement #//EngineeredElement #//Capability">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Something leveraged by an actor to perform an activity. For example - a tool."/>
    </eAnnotations>
    <eAnnotations source="urn:org.nasdanika">
      <details key="label_ru" value="Ресурс"/>
      <details key="documentation_ru" value="Ресурс - объект, позволяющий исполнителю выполнять работу. Например, какой либо инструмент"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Resource" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Resource can be nested. E.g. a virtual machine may host a web server."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Вложенные ресурсы"/>
        <details key="documentation_ru" value="Ресурсы могут быть вложенными, многокомпонентными. Например, виртуальная машина может включать в себя веб-сервер."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifacts" upperBound="-1"
        eType="#//Artifact" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Resources may host artifacts."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Артефакт"/>
        <details key="documentation_ru" value="Ресурсы могут включать в себя артефакты"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Transition from its containing source element to a target element. May pass artifacts in both directions. E.g. a transition to &quot;Commit code&quot; may take &quot;Source code&quot; as input and return &quot;Commit ID&quot; as a result."/>
    </eAnnotations>
    <eAnnotations source="urn:org.nasdanika">
      <details key="label_ru" value="Переход (передача)"/>
      <details key="documentation_ru" value="Переход (передача) промежуточных результатов работ/операций от элемента-источника к целевому элементу. Артифакты могут передаваться в обоих направлениях. Например, переход к «Фиксирующему коду» может принимать «Исходный код» в качестве ввода и возвращать «Фиксированный код» в результате.&#xA; "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Target" eOpposite="#//Target/inboundTransitions">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Transition target."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Целевой элемент"/>
        <details key="documentation_ru" value="Работа/операция, являющаяся целью передачи артефакта, выполнение которой невозможно до выполнения работы-источника артефакта."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//Artifact">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Artifacts passed by the source to the transition and delivered to the target."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Входящие артефакты"/>
        <details key="documentation_ru" value="Артефакты предаваемые от элемента-источника к целевому элементу через переход."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="results" upperBound="-1"
        eType="#//Artifact">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Artifacts returned by the target to be delivered to the source."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Результат передачи"/>
        <details key="documentation_ru" value="Артефакты возвращаемые целевым элементом элементу источнику."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A generic relationship between model elements."/>
    </eAnnotations>
    <eAnnotations source="urn:org.nasdanika">
      <details key="label_ru" value="Ассоциация"/>
      <details key="documentation_ru" value="Отношения наследования между элементами модели"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//PackageElement">
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Цель"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Engineer" eSuperTypes="#//PackageElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Engineers own engineered elements and are assigned issues associated with these elements."/>
    </eAnnotations>
    <eAnnotations source="urn:org.nasdanika">
      <details key="label_ru" value="Инженер"/>
      <details key="documentation_ru" value="Специалист, владеющий каким-либо ресурсом, процессом или элементом процесса и получающий задачи, связанные с этим процессом или ресуром."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owns" upperBound="-1" eType="#//EngineeredElement"
        eOpposite="#//EngineeredElement/owners">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Elements which this engineer owns. Ownership is propagated down to child elements recursively, unless these elements have an explicitly assigned owner. Also issues associated with owned elements and not having an engineer explicitly assigned to them are implicitly assigned to the element owner."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Хозяйство"/>
        <details key="documentation_ru" value="Совокупность элементов, которыми владеет инженер. &#xA;Владение распространяется до дочерних элементов рекурсивно, если только эти элементы не имеют явно назначенного владельца. Также проблемы, связанные с собственными элементами и отсутствием явно назначенного им инженера, неявно назначаются владельцу элемента."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignments" upperBound="-1"
        eType="#//Issue" eOpposite="#//Issue/assignedTo">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Engineer's assigned issues."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Задача"/>
        <details key="documentation_ru" value="Задачи, переданные инженеру на исполнение"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Issue" eSuperTypes="#//ModelElement #//Requirement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Something to possibly act on regarding the owning element - a problem/pain point, an improvement opportunity/enhancement.&#xA;&#xA;Example:&#xA;&#xA;* Containing activity - &quot;Initial setup of a software project&quot;, &#xA;* Size - 4.0 (hours) - copy an existing project and modify its sources.&#xA;* Issue - &quot;Create a code generator&quot; (enhancement),&#xA;    * Size - 40.0 (hours).&#xA;    * Benefit - 3.5 (hours).&#xA;    * Implementation - an activity providing a detailed explanation how code generator shall be implemented."/>
    </eAnnotations>
    <eAnnotations source="urn:org.nasdanika">
      <details key="label_ru" value="Задача"/>
      <details key="documentation_ru" value="Что-то, требующее выполнения какой-либо работы в отношении элемента-владельца - ошибка, проблема, инцедент, возможность усовершенствования."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importance" eType="#//IssueImportance"
        defaultValueLiteral="Medium">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issue importance."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//IssueStatus"
        defaultValueLiteral="Open">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issue status."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedTo" eType="#//Engineer"
        eOpposite="#//Engineer/assignments">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Engineer this issue is assigned to. If this attribute is null the issue is assumed to be assigned to the owner of the containing element."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An estimation of effort required to complete this issue in some units used consistently throughout the model - points, person hours, dollars."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="benefit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An estimation of reduction of the containing activity effort caused by completion of this issue. It can be used for cost/benefit analysis in order to prioritize issues."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Issue" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issues may be organized into a hierarchy."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementation" eType="#//Activity">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Activity providing details about how to implement this issue.&#xA;&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IssueStatus">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Issue status."/>
    </eAnnotations>
    <eLiterals name="Open" literal="Open">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An issue which hasn't been worked on."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="InProgress" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Work in progress."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="Done" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Work completed."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="Cancelled">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The issue is not going to be worked on for some reason."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IssueImportance">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Importance of the issue."/>
    </eAnnotations>
    <eLiterals name="Low">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Low importance."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="Medium" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Medium importance."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="High" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="High importance."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
</ecore:EPackage>
