<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="engineering" nsURI="urn:org.nasdanika.engineering" nsPrefix="org.nasdanika.engineering">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="A model of engineering - a process of building something composite by resolving issues associated with solution components by engineers in increments and making the new functionality available in releases."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="EngineeredElement" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base class for elements which have an owning engineer and may contain issues."/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
